language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: sally.yeung@sas.com
  api: https://api.run.pivotal.io
  organization: sallyyeung
  space: development
  password:
    secure: nRfy330QX7h4FOviGewmBbPrzsUe19zU04lbp6no4ZTN2eRxSljlnrPYJY8CWVlWzIAKF3hWEXwvtNGxqbbQhlB5xiOykprKOg296YKbrIVl9fnb0ggjqFfd1NnYnSnYO5lz610MrUi1a71JCRJTfVFxBwBWoSzHRmiziHQqk8K3nmYwoEO+fI7+XKfWxHqJ8A3myYu/dJ8FCyv9eyGvW0F7lHQJQrSm83/RK0QAzLoyTFqSjsbVhAWSOPFyGIURBvC3ag4d4WGZNPFDzmdw3HAEDpLy6fyegIqJ9BzbaJG1RGniQYNAPWX9ddDWbYACHTMvU1hHqX+8Mxqtzag0/rEupN9LP/gZNlu3q3ER12czyKvxVyzwRYqwBD0LKa+fS8t+PLpfB/DbYf2tTOL/4NxYyZ3rH5kDdve3JcD8ZbjZM5D503s6Af+kHRwdzTtR+Vh40d9v/JfUm8DEDTHY+FYIVFBN95soklL3CwdcLRuLJqz4TtLVwM4HDLUraPJsOYY8XkhYJO/ROY6ZLbNW7mHvoC9RrCec95E9PakoVMrvNRSlglRm9k6+aLrHZF1z9J5sPvhr7rnr8MUL69Jhqz8GAb82EVKLZ8+lAaTf9+tzkfRRS0RqC68OkIVKwAma1KvCXLMAq89YOONRzIXkVwigcRDQvnL3hToduPCdhv4=
